# Generated by Django 2.1.5 on 2019-02-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lession',
            name='number_of_students',
            field=models.IntegerField(),
        ),
    ]
