# Generated by Django 2.1.5 on 2019-02-11 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eng_classes',
            name='class_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.RemoveField(
            model_name='eng_classes',
            name='students_enrolled',
        ),
        migrations.AddField(
            model_name='eng_classes',
            name='students_enrolled',
            field=models.ManyToManyField(to='students.students'),
        ),
    ]
