# Generated by Django 2.1.5 on 2019-02-16 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_teacher_email'),
        ('classes', '0007_remove_eng_classes_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='eng_classes',
            name='class_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
            preserve_default=False,
        ),
    ]
