# Generated by Django 2.1.5 on 2019-02-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('classes', '0008_eng_classes_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='eng_classes',
            name='students_enrolled',
            field=models.ManyToManyField(related_name='participants', to='students.students'),
        ),
    ]
