# Generated by Django 2.1.5 on 2019-02-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eng_classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.CharField(max_length=250)),
                ('class_teacher', models.CharField(max_length=250)),
                ('students_enrolled', models.TextField()),
            ],
        ),
    ]
