# Generated by Django 2.1.5 on 2019-02-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20190211_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eng_classes',
            name='students_enrolled',
            field=models.ManyToManyField(related_name='participants', to='students.students'),
        ),
    ]
