# Generated by Django 2.1.5 on 2019-02-16 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20190216_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eng_classes',
            name='students_enrolled',
        ),
    ]
